# Generated by Django 5.0.6 on 2026-06-08 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='collection_covers/')),
                ('is_promoted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
                ('series', models.ManyToManyField(blank=True, related_name='collections', to='library.series')),
            ],
            options={
                'db_table': 'collections_collection',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='readinglist_covers/')),
                ('is_promoted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collections_reading_list',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SmartFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('criteria', models.JSONField(default=dict)),
                ('sort_by', models.CharField(default='sort_name', max_length=50)),
                ('sort_asc', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collections_smart_filter',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReadingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_list_items', to='library.chapter')),
                ('reading_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='collections.readinglist')),
            ],
            options={
                'db_table': 'collections_reading_list_item',
                'ordering': ['order'],
                'unique_together': {('reading_list', 'chapter')},
            },
        ),
        migrations.CreateModel(
            name='WantToRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='want_to_read', to='library.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='want_to_read', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collections_want_to_read',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'series')},
            },
        ),
    ]
