# Generated by Django 5.0.6 on 2026-06-08 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pages_read', models.BigIntegerField(default=0)),
                ('total_chapters_read', models.IntegerField(default=0)),
                ('total_series_read', models.IntegerField(default=0)),
                ('total_reading_time_minutes', models.BigIntegerField(default=0)),
                ('last_aggregated', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stats_user_stats',
            },
        ),
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages_read', models.IntegerField(default=0)),
                ('read_at', models.DateField()),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_history', to='library.chapter')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to='library.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stats_reading_history',
                'ordering': ['-read_at'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='stats_readi_user_id_236989_idx'), models.Index(fields=['user', 'series'], name='stats_readi_user_id_24059f_idx')],
            },
        ),
    ]
