# Generated by Django 5.0.6 on 2026-06-08 15:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('primary_color', models.CharField(blank=True, default='#6366f1', max_length=7)),
                ('age_restriction', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Everyone'), (2, 'Teen'), (3, 'Mature'), (4, 'Adults Only')], default=0)),
                ('age_restriction_include_unknowns', models.BooleanField(default=True)),
                ('identity_provider', models.CharField(choices=[('local', 'Local'), ('oidc', 'OpenID Connect')], default='local', max_length=10)),
                ('oidc_id', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('read_only', 'Read Only')], default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('reading_direction', models.CharField(choices=[('ltr', 'Left to Right'), ('rtl', 'Right to Left'), ('ttb', 'Top to Bottom')], default='ltr', max_length=20)),
                ('reading_mode', models.CharField(choices=[('single', 'Single Page'), ('double', 'Double Page'), ('webtoon', 'Webtoon')], default='single', max_length=20)),
                ('scaling', models.CharField(choices=[('fit_screen', 'Fit Screen'), ('fit_height', 'Fit Height'), ('fit_width', 'Fit Width'), ('original', 'Original')], default='fit_screen', max_length=20)),
                ('theme', models.CharField(default='dark', max_length=20)),
                ('book_font_size', models.IntegerField(default=16)),
                ('book_font_family', models.CharField(default='serif', max_length=100)),
                ('book_line_spacing', models.FloatField(default=1.5)),
                ('blur_unread_summaries', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'accounts_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(default='OPDS', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_api_key',
            },
        ),
    ]
