# Generated by Django 5.0.6 on 2026-06-08 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_scroll_id', models.CharField(max_length=500)),
                ('highlighted_text', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('color', models.CharField(default='#facc15', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='library.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reader_annotation',
                'ordering': ['book_scroll_id'],
            },
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('pages_read', models.IntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='library.chapter')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='library.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reader_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(default=0)),
                ('book_scroll_id', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='library.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reader_bookmark',
                'ordering': ['chapter', 'page'],
                'unique_together': {('user', 'chapter', 'page')},
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages_read', models.IntegerField(default=0)),
                ('book_scroll_id', models.CharField(blank=True, max_length=500)),
                ('total_reads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='library.chapter')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='library.library')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='library.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reader_progress',
                'indexes': [models.Index(fields=['user', 'series'], name='reader_prog_user_id_2aa998_idx'), models.Index(fields=['user', 'library'], name='reader_prog_user_id_302589_idx')],
                'unique_together': {('user', 'chapter')},
            },
        ),
    ]
